## Write a pipeline for the file metadata movie

### step 1 : 
    dowload raw data file from 'https://raw.githubusercontent.com/RiccardoRubini93/Academy/main/movie_metadata_raw.csv' and save it in a folder call Raw/day=date/
    
### step 2:
    load raw data file in pandas dataframe perform data exploration and cleaning and save into 
    Clean/day=date with name movie_metadata_clean.csv

### step 3:
    load clead data perform aggregation and save into 
    layer_2/day=date with name movie_metadata_aggergated.csv

step 1): 
raw/day=today_date(2023-04-20)/movie_metadata_raw.csv

In [1]:
import os 
import requests
import pandas as pd 
from datetime import date

In [17]:
def download(url,dest_folder):
    
    if not os.path.exists(dest_folder):
        os.makedirs(dest_folder)
    
    file_name = url.split('/')[-1]
    file_path = os.path.join(dest_folder,file_name)
    
    r = requests.get(url)
    
    if r.ok:
        print(f'Saving file to {file_path}')
        with open(file_path,'wb') as f:
            f.write(r.content)
        f.close()
        
    else: print(f'Failed with code : {r.status_code}')

In [18]:
today = date.today().strftime('%Y-%m-%d')
dest_folder = f'raw/day={today}'
url = 'https://raw.githubusercontent.com/RiccardoRubini93/Academy/main/movie_metadata_raw.csv'

download(url,dest_folder)

Saving file to raw/day=2023-04-20\movie_metadata_raw.csv

### import files in pandas DF

In [21]:
file_name = 'movie_metadata_raw.csv'
file_path_raw = f'{dest_folder}/{file_name}'
print(file_path_raw)

raw/day=2023-04-20/movie_metadata_raw.csv

In [22]:
df = pd.read_csv(file_path_raw)

In [25]:
df.shape

(5043, 28)

In [26]:
df.head(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [27]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [29]:
df.isna().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [30]:
cols = ['director_name','movie_title','gross']
df[cols]

,director_name,movie_title,gross
0,James Cameron,Avatar,760505847.0
1,Gore Verbinski,Pirates of the Caribbean: At World's End,309404152.0
2,Sam Mendes,Spectre,200074175.0
3,Christopher Nolan,The Dark Knight Rises,448130642.0
4,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,NaN
...,...,...,...
5038,Scott Smith,Signed Sealed Delivered,NaN
5039,NaN,The Following,NaN
5040,Benjamin Roberds,A Plague So Pleasant,NaN
5041,Daniel Hsia,Shanghai Calling,10443.0
5042,Jon Gunn,My Date with Drew,85222.0

In [36]:
df.iloc[1] == df[1:2]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [38]:
df[df['gross']>1000]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [41]:
df[df['director_name'].notna()]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### Ordinare df in base al gross revenue e al budget in ordine discendente
una volta generato df_sorted mostrare le prime 10 righe solo per director_name,gross,budget

In [45]:
print(df)

      color      director_name  num_critic_for_reviews  duration
0     Color      James Cameron                   723.0     178.0  \
1     Color     Gore Verbinski                   302.0     169.0
2     Color         Sam Mendes                   602.0     148.0
3     Color  Christopher Nolan                   813.0     164.0
4       NaN        Doug Walker                     NaN       NaN
...     ...                ...                     ...       ...
5038  Color        Scott Smith                     1.0      87.0
5039  Color                NaN                    43.0      43.0
5040  Color   Benjamin Roberds                    13.0      76.0
5041  Color        Daniel Hsia                    14.0     100.0
5042  Color           Jon Gunn                    43.0      90.0

      director_facebook_likes  actor_3_facebook_likes      actor_2_name
0                         0.0                   855.0  Joel David Moore  \
1                       563.0                  1000.0     Orlando Bloom
2                         0.0                   161.0      Rory Kinnear
3                     22000.0                 23000.0    Christian Bale
4                       131.0                     NaN        Rob Walker
...                       ...                     ...               ...
5038                      2.0                   318.0     Daphne Zuniga
5039                      NaN                   319.0     Valorie Curry
5040                      0.0                     0.0     Maxwell Moody
5041                      0.0                   489.0     Daniel Henney
5042                     16.0                    16.0  Brian Herzlinger

      actor_1_facebook_likes        gross                           genres
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  \
1                    40000.0  309404152.0         Action|Adventure|Fantasy
2                    11000.0  200074175.0        Action|Adventure|Thriller
3                    27000.0  448130642.0                  Action|Thriller
4                      131.0          NaN                      Documentary
...                      ...          ...                              ...
5038                   637.0          NaN                     Comedy|Drama
5039                   841.0          NaN     Crime|Drama|Mystery|Thriller
5040                     0.0          NaN            Drama|Horror|Thriller
5041                   946.0      10443.0             Comedy|Drama|Romance
5042                    86.0      85222.0                      Documentary

      ... num_user_for_reviews language  country  content_rating       budget
0     ...               3054.0  English      USA           PG-13  237000000.0  \
1     ...               1238.0  English      USA           PG-13  300000000.0
2     ...                994.0  English       UK           PG-13  245000000.0
3     ...               2701.0  English      USA           PG-13  250000000.0
4     ...                  NaN      NaN      NaN             NaN          NaN
...   ...                  ...      ...      ...             ...          ...
5038  ...                  6.0  English   Canada             NaN          NaN
5039  ...                359.0  English      USA           TV-14          NaN
5040  ...                  3.0  English      USA             NaN       1400.0
5041  ...                  9.0  English      USA           PG-13          NaN
5042  ...                 84.0  English      USA              PG       1100.0

      title_year actor_2_facebook_likes imdb_score  aspect_ratio
0         2009.0                  936.0        7.9          1.78  \
1         2007.0                 5000.0        7.1          2.35
2         2015.0                  393.0        6.8          2.35
3         2012.0                23000.0        8.5          2.35
4            NaN                   12.0        7.1           NaN
...          ...                    ...        ...           ...
5038      2013.0                  470.0        7.7           NaN
5039         NaN                  593.0        7.5         16.00
5040      2013.0                    0.0        6.3           NaN
5041      2012.0                  719.0        6.3          2.35
5042      2004.0                   23.0        6.6          1.85

     movie_facebook_likes
0                   33000
1                       0
2                   85000
3                  164000
4                       0
...                   ...
5038                   84
5039                32000
5040                   16
5041                  660
5042                  456

[5043 rows x 28 columns]

In [43]:
df_sorted

NameError: name 'df_sorted' is not defined